### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by dioscarr** [Apt3kStudio/Web#19]
Create a home page for web app 

(events need to be wired correctly)

[AB#4](https://dev.azure.com/apt3k/c5feb228-4d70-4dd7-babc-9a8a0e967f9c/_workitems/edit/4)

**Comment by dioscarr** [comment]
@nvasquedr 
## Requirements
Add a new section to the landing page call **Events**

### Top Level.
- [ ] Add a new property to the LandingPage entity.  -> Data folder. New migration is required.
- [ ] Add a new property to the Landing Page View Model.
- [ ] Add the property to the Load method
- [ ] Map the new property to the cshtml file

### Admin Level
- [ ] Add a new property to the Landing Page View Model
- [ ] Add the property to the Load method
- [ ] Add the property to the update method. The property should be map on two places. Update section and insert section.
- [ ] Map the new property to the cshtml file and make sure to add a unique ID to the html element. 
- [ ] go to the wwwroot folder. Expand the JS and open site.js. Apply ckeditor to the new element using the id. 

### Refactoring
- [ ] The landingPageVM => update method. There should be an Insert method and an update method. Right now there is only an update that is exedcuting both logic. They should be handle separately. 


### wwwroot
This folder contains the css and the js logic. Please place all of your JS logic on this folder. 

***

## layout
[Assets](https://drive.google.com/file/d/1Y3anOSxFft1ZGvGyiuPKsjjWXpG93vPb/view)

**Comment by jagomez16** [comment]
[Product description](https://drive.google.com/open?id=1TPhrmJSsiDc8F3E7vp6RneKdtlq8U7nOJ9d8CizsP9E)

**Comment by jagomez16** [comment]
Test 2
