### ISSUE TITLE
Create a Push notification system WebApi to phone App

### ISSUE THREAD

**Issue by dioscarr** [Apt3kStudio/Web#2]
Creating a new feature to handle notification from web api to phone app. 
We will use Firebase as the intermediary technology. 

[AB#6](https://dev.azure.com/apt3k/c5feb228-4d70-4dd7-babc-9a8a0e967f9c/_workitems/edit/6)

**Comment by dioscarr** [comment]
Im plementation guide: https://medium.com/kzsoftworks/firebase-push-notifications-using-a-net-backend-dc91fcc39672
https://cdn-images-1.medium.com/max/1600/1*_9J4Zpijs25MZJrAk9X1aA.png

**Comment by jagomez16** [comment]
In what release this issue should be included @dioscarr?
