### ISSUE TITLE
Device Class

### ISSUE THREAD

**Issue by dioscarr** [Apt3kStudio/Web#29]
# Device Class
The device class is an abstract of a mobile device. The followings are properties defined in the class:
- [x] public int Id { get; set; }
- [x] public string  Name { get; set; }
- [x] public int UserId { get; set; }
- [x] public string FCMToken { get; set; }
- [x] public Events EventToBeSend { get; set; }
**Methods**
The following method create an intance of the Events class.
- [x] SetEventToBeSend()
The following method sends physical device a message containing an event.
- [x] SendMessageAsync()

**Comment by jagomez16** [comment]
Revisit this issue to see if we can extend the functionality of the class.

The device class represents a device

- class should be able to handle its functions 

- we should go back to restructure this class

- include push notification code to this class
